# Generated by Django 4.0 on 2022-06-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WiseTestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Time at which test will start')),
                ('duration', models.IntegerField(help_text='Duration in Minutes')),
                ('marks_awarded_per_correct_ans', models.IntegerField(help_text='Marks awarded per correct answer')),
                ('marks_deducted_per_incorrect_ans', models.IntegerField(help_text='Marks deducted per incorrect answer')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], help_text='whether user is a student or teacher', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(help_text='date published'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(help_text='Marks in interger type')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='WiseTestApp.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='WiseTestApp.appuser')),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='WiseTestApp.question')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'position'), ('question', 'choice')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='WiseTestApp.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WiseTestApp.usertype'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
