# Generated by Django 4.0 on 2022-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiseTestApp', '0003_test_created_by_test_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
